name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - setup.py

jobs:
  build_and_deploy:
    if: ${{ github.repository_owner == 'developomp' }} # prevents workflow from running in forked repos
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Archive Artifact
        uses: actions/upload-artifact@v2
        with:
          name: setup
          path: setup.py

      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: setup
          path: setup.py

      - name: Deploy
        run: |
          git config --local user.email "developomp@users.noreply.github.com"
          git config --local user.name "developomp"
          mv ./setup.py ./index.html  # overwrite index.html
          git commit -ma "auto deploy from workflow"
          git push
